### ISSUE TITLE
failed launch portable and main version

### ISSUE THREAD

**Issue by llimonix** [Storik4pro/goodbyeDPI-UI#10]
Traceback (most recent call last):
  File "src\main.py", line 19, in <module>
  File "E:\goodbyeDPI UI\_internal\_data.py", line 86, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "E:\goodbyeDPI UI\_internal\_data.py", line 78, in __init__
    self.settings = self.reload_settings()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\goodbyeDPI UI\_internal\_data.py", line 82, in reload_settings
    config.read(SETTINGS_FILE_PATH, encoding='utf-8')
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 245: invalid continuation byte

**Comment by Storik4pro** [comment]
Откройте файл `settings.ini` по пути `_internal\data\settings` и пришлите его содержимое сюда

**Comment by llimonix** [comment]
[APPEARANCE_MODE]
mode = dark
use_mica = True

[REGION]
region = RU

[GLOBAL]
is_first_run = True
language = RU
change_dns = False
autorun = False
hide_to_tray = False
use_advanced_mode = False
version = 1.1.0
work_directory = "/"
after_update = True
lastcheckedtime = 00:00 01.01.2000
updatesavailable = False
notifyaboutupdates = True
version_to_update = 
usebetafeatures = False
update_coplete = False
engine = zapret

[COMMANDS]
russia_blacklist = -9, --blacklist, ..//russia-blacklist.txt, --blacklist, ..//russia-youtube.txt
russia_blacklist_dnsredir = -9, --dns-addr, 77.88.8.8, --dns-port, 1253, --dnsv6-addr, 2a02:6b8::feed:0ff, --dnsv6-port, 1253, --blacklist, ..//russia-blacklist.txt, --blacklist, ..//russia-youtube.txt
any_contry = -9
any_contry_dnsredir = -9, --dns-addr, 77.88.8.8, --dns-port, 1253, --dnsv6-addr, 2a02:6b8::feed:0ff, --dnsv6-port, 1253

[GOODBYEDPI]
preset = 10
dns = False
dns_value = 77.88.8.8
dns_port = False
dns_port_value = 1253
dnsv6 = False
dnsv6_value = 2a02:6b8::feed:0ff
dnsv6_port = False
dnsv6_port_value = 1253
use_blacklist = True
use_blacklist_custom = True
blockpassivedpi = False
blockquic = False
replacehost = False
removespace = False
mixhostcase = False
donotwaitack = False
additionalspace = False
processallports = False
allownosni = False
dnsverbose = False
wrongchecksum = False
wrongseq = False
nativefrag = False
reversefrag = False
httpfragmentation = False
httpfragmentation_value = 2
httpkeepalive = False
httpkeepalive_value = 2
httpsfragmentation = False
httpsfragmentation_value = 2
maxpayload = False
maxpayload_value = 1200
additionalport = False
additionalport_value = 2710
ipid = False
ipid_value = 54321
blacklist_value = 
minttl_value = 3
autottl_value = 1
setttl_value = 5
autottl = False
minttl = False
blacklist = False
setttl = False
fakefromhex = False
fakefromhex_value = 160301FFFF01FFFFFF0303594F5552204144564552544953454D454E542048455245202D202431302F6D6F000000000009000000050003000000
fakegen = False
fakegen_value = 5
fakeresend = False
fakeresend_value = 1
custom_parameters = 

[ZAPRET]
use_advanced_mode = False
custom_parameters = 
discord_string = --wf-tcp 443-65535 --wf-udp 443-65535 --filter-udp 443 --hostlist list-discord.txt --dpi-desync fake --dpi-desync-udplen-increment 10 --dpi-desync-repeats 6 --dpi-desync-udplen-pattern 0xDEADBEEF --dpi-desync-fake-quic quic_initial_www_google_com.bin --new --filter-udp 50000-65535 --dpi-desync fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic quic_initial_www_google_com.bin --new --filter-tcp 443 --hostlist list-discord.txt --dpi-desync fake,split2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --dpi-desync-fake-tls tls_clienthello_www_google_com.bin
youtube_string = --wf-l3 ipv4 --wf-tcp 443 --wf-udp 1-65535 --filter-udp 50000-65535 --dpi-desync fake --dpi-desync-cutoff d4 --dpi-desync-repeats 6 --dpi-desync-any-protocol --new --dpi-desync fake,split2 --dpi-desync-fooling badseq --dpi-desync-fake-tls tls_clienthello_www_google_com.bin --hostlist list-youtube.txt
youtube_discord_alt = --wf-tcp 80,443,50000-65535 --wf-udp 443,50000-65535 --filter-udp 443 --hostlist list-general.txt --dpi-desync fake --dpi-desync-udplen-increment 10 --dpi-desync-repeats 6 --dpi-desync-udplen-pattern 0xDEADBEEF --dpi-desync-fake-quic quic_initial_www_google_com.bin --new --filter-udp 50000-65535 --dpi-desync fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic quic_initial_www_google_com.bin --new --filter-tcp 80 --dpi-desync fake,split2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --new --filter-tcp 443 --hostlist list-general.txt --dpi-desync fake,split2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --dpi-desync-fake-tls tls_clienthello_www_google_com.bin --new --dpi-desync fake,disorder2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig
youtube_discord = --wf-l3 ipv4 --wf-tcp 443 --wf-udp 1-65535 --filter-udp 50000-65535 --dpi-desync fake --dpi-desync-cutoff d4 --dpi-desync-repeats 6 --dpi-desync-any-protocol --new --dpi-desync fake,split2 --dpi-desync-fooling badseq --dpi-desync-fake-tls tls_clienthello_www_google_com.bin --hostlist  list-youtube.txt  --new --wf-tcp 443-65535 --wf-udp 443-65535 --filter-udp 443 --hostlist  list-discord.txt  --dpi-desync fake --dpi-desync-udplen-increment 10 --dpi-desync-repeats 6 --dpi-desync-udplen-pattern 0xDEADBEEF --dpi-desync-fake-quic  quic_initial_www_google_com.bin  --new --filter-udp 50000-65535 --dpi-desync fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic  quic_initial_www_google_com.bin  --new --filter-tcp 443 --hostlist  list-discord.txt  --dpi-desync fake,split2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --dpi-desync-fake-tls  tls_clienthello_www_google_com.bin
enableparallelstart = False
preset = 3

**Comment by Storik4pro** [comment]
Мне нужна дополнительная информация для выявления проблемы.
1. На какой версии Windows возникла проблема (Например, Windows 10 22H2)
2. Какой язык вы используете в Windows
3. Пришлите сюда ваш `settings.ini` **файл**, чтобы я мог проверить наличие неправильных символов в файле

Что можно сделать прямо сейчас:

-  Проверьте кодировку вашего `settings.ini` файла. Откройте файл в блокноте и убедитесь, что кодировка - `"UTF-8"`. Если это не так, то сохраните файл с кодировкой `"UTF-8"`

**Comment by llimonix** [comment]
Windows 10 22H2
Русский
![image](https://github.com/user-attachments/assets/2eb5af88-2923-42dd-bd84-82457952b136)
https://dropmefiles.com/50kGh - SETTINGS.INI 

Стоит кодировка UTF-8
![image](https://github.com/user-attachments/assets/df63e169-8392-48b6-bb94-a88a5ebbc733)

**Comment by Storik4pro** [comment]
Проверьте имя вашего ПК в локальной сети. Оно не должно содержать кириллицу

**Comment by llimonix** [comment]
С этим тоже все нормально. Ничего не перекачивал, запустил снова тот же файл и он почему то заработал. Может быть это все таки что то с файлом и после его открытия и закрытия оно починилось. Но не уверен

**Comment by Storik4pro** [comment]
Рад, что проблема решилась. Если у вас будут предложения, из-за чего это могло произойти, то обязательно напишите
