### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Koaxz** [Storik4pro/goodbyeDPI-UI#11]
[DEBUG] Connecting to winws.exe ...

GoodbyeDPI v0.2.3rc3: Passive DPI blocker and Active DPI circumvention utility

https://github.com/ValdikSS/GoodbyeDPI

 unknown option -- wf-tcp

Usage: goodbyedpi.exe [OPTION...]

 -p          block passive DPI

 -q          block QUIC/HTTP3

 -r          replace Host with hoSt

 -s          remove space between host header and its value

 -a          additional space between Method and Request-URI (enables -s, may break sites)

 -m          mix Host header case (test.com -> tEsT.cOm)

 -f <value>  set HTTP fragmentation to value

 -k <value>  enable HTTP persistent (keep-alive) fragmentation and set it to value

 -n          do not wait for first segment ACK when -k is enabled

 -e <value>  set HTTPS fragmentation to value

 -w          try to find and parse HTTP traffic on all processed ports (not only on port 80)

 --port        <value>    additional TCP port to perform fragmentation on (and HTTP tricks with -w)

 --ip-id       <value>    handle additional IP ID (decimal, drop redirects and TCP RSTs with this ID).

 --dns-addr    <value>    redirect UDPv4 DNS requests to the supplied IPv4 addrexperimental)

 --dns-port    <value>    redirect UDPv4 DNS requests to the supplied port (53 b

by default)

 --dnsv6-addr  <value>    redirect UDPv6 DNS requests to the supplied IPv6 addre

ess (experimental)

 --dnsv6-port  <value>    redirect UDPv6 DNS requests to the supplied port (53 b

by default)

 --dns-verb               print verbose DNS redirection messages

 --blacklist   <txtfile>  perform circumvention tricks only to host names and su

ubdomains from

                          supplied text file (HTTP Host/TLS SNI).

                          This option can be supplied multiple times.

 --allow-no-sni           perform circumvention if TLS SNI can't be detected wit

th --blacklist enabled.

 --frag-by-sni            if SNI is detected in TLS packet, fragment the packet 

 right before SNI value.

 --set-ttl     <value>    activate Fake Request Mode and send it with supplied T

TTL value.

                          DANGEROUS! May break websites in unexpected ways. Use 

 with care (or --blacklist).

 --auto-ttl    [a1-a2-m]  activate Fake Request Mode, automatically detect TTL a

and decrease

                          it based on a distance. If the distance is shorter tha

an a2, TTL is decreased

                          by a2. If it's longer, (a1; a2) scale is used with the

e distance as a weight.

                          If the resulting TTL is more than m(ax), set it to m. 
                          Default (if set): --auto-ttl 1-4-10. Also sets --min-t

ttl 3.

                          DANGEROUS! May break websites in unexpected ways. Use 

 with care (or --blacklist).

 --min-ttl     <value>    minimum TTL distance (128/64 - TTL) for which to send 

 Fake Request

                          in --set-ttl and --auto-ttl modes.

 --wrong-chksum           activate Fake Request Mode and send it with incorrect 

 TCP checksum.

                          May not work in a VM or with some routers, but is safe

er than set-ttl.

                          Could be combined with --set-ttl

 --wrong-seq              activate Fake Request Mode and send it with TCP SEQ/AC

CK in the past.

 --native-frag            fragment (split) the packets by sending them in smalle

er packets, without

                          shrinking the Window Size. Works faster (does not slow

w down the connection)

                          and better.

 --reverse-frag           fragment (split) the packets just as --native-frag, bu

ut send them in the

                          reversed order. Works with the websites which could no

ot handle segmented

                          HTTPS TLS ClientHello (because they receive the TCP fl

[23;80
[DEBUG] The winws.exe process has been terminated by user

**Comment by Storik4pro** [comment]
Вы пытаетесь запустить Zapret или GoodbyeDPI?

**Comment by Storik4pro** [comment]
Попробуйте перезапустить UI

**Comment by Storik4pro** [comment]
Какая версия UI у вас установлена? Проблема появилась после обновления?

Так же 
- Откройте файл `settings.ini` расположенный в `_internal\data\settings`. Проверьте, что параметр `engine` имеет значение  `zapret`. 
- Попробуйте включить движок `goodbyeDPI`, перезапустите приложение, а затем снова поставьте `zapret`
- Проверьте, что `winws.exe` существует по пути `_internal\data\zapret`

**Comment by Storik4pro** [comment]
Попробуйте скачать предыдущую [версию 1.1.4](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.1.4). 
Возможно на ней подобной проблемы не будет

**Comment by Storik4pro** [comment]
Покажите вывод goodbyeDPI

**Comment by Storik4pro** [comment]
Перейдите в инструменты -> просмотр вывода процесса

**Comment by Storik4pro** [comment]
Хорошо, перейдите в папку `_internal\data\zapret` и запустите `winws.exe`. Пришлите скриншот вывода `winws.exe` сюда

**Comment by Storik4pro** [comment]
Нажмите Win+R введите в поиске cmd и с зажатыми SHIFT+CTRL нажмите ENTER. 
Скопируйте путь к `winws.exe` в консоль и нажмите ENTER

**Comment by Storik4pro** [comment]
Хм. Это странно.
Попробуйте в параметрах zapret ввести строку в дополнительные параметры 
```
--blacklist ..\\russia-blacklist.txt --blacklist list-youtube.txt --wf-l3 ipv4 --wf-tcp 443 --wf-udp 1-65535 --filter-udp 50000-65535 --dpi-desync fake --dpi-desync-cutoff d4 --dpi-desync-repeats 6 --dpi-desync-any-protocol --new --dpi-desync fake,split2 --dpi-desync-fooling badseq --dpi-desync-fake-tls tls_clienthello_www_google_com.bin --hostlist  list-youtube.txt  --new --wf-tcp 443-65535 --wf-udp 443-65535 --filter-udp 443 --hostlist  list-discord.txt  --dpi-desync fake --dpi-desync-udplen-increment 10 --dpi-desync-repeats 6 --dpi-desync-udplen-pattern 0xDEADBEEF --dpi-desync-fake-quic  quic_initial_www_google_com.bin  --new --filter-udp 50000-65535 --dpi-desync fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic  quic_initial_www_google_com.bin  --new --filter-tcp 443 --hostlist  list-discord.txt  --dpi-desync fake,split2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --dpi-desync-fake-tls  tls_clienthello_www_google_com.bin
```
И покажите итоговый вывод

**Comment by Storik4pro** [comment]
Вы включили переключатель "Запускать zapret с параметрами, заданными вручную"?

**Comment by Storik4pro** [comment]
Попробуйте скачать и установить [последнюю версию 1.2.1](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.1). Я внес исправления, которые потенциально могли решить эту проблему
