### ISSUE TITLE
Add the ability for the zapret engine to contribute your sites

### ISSUE THREAD

**Issue by PhantomX5571** [Storik4pro/goodbyeDPI-UI#13]
I noticed that when choosing the zapret engine, there is no text file for entering links to sites to bypass the lock.

P.S.
If there is such a text file and I did not notice it, please tell me where it is.

**Comment by Storik4pro** [comment]
Now you can change the list of sites for zapret using the path `_internal\data\zapret`. The files are `list-discord.txt` (to bypass RTS - calls) and `list-youtube.txt`. In the future, a corresponding button will appear in the parameters

**Comment by PhantomX5571** [comment]
> Теперь можно менять список сайтов для запрета, используя путь `_internal\data\zapret`. Файлы находятся `list-discord.txt`(для обхода RTS - вызовов) и `list-youtube.txt`. В дальнейшем соответствующая кнопка появится в параметрах
Спасибо :)

**Comment by Storik4pro** [comment]
Было добавлено в [обновлении 1.2.2](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.2)
