### ISSUE TITLE
Бесконечное подключение к RTC в дискорде

### ISSUE THREAD

**Issue by xleb-normal** [Storik4pro/goodbyeDPI-UI#15]
У меня в настройках выбран zapret, но почему-то к войсам всё равно не подключает

**Comment by Storik4pro** [comment]
Вы пробовали изменить пресет на альтернативный?

**Comment by xleb-normal** [comment]
> Вы пробовали изменить пресет на альтернативный?

Пробовал, всё точно так же висит подключение к RTC и всё

**Comment by Storik4pro** [comment]
Попробуйте следующие действия: 
1. **Обновите Zapret.** Перейдите в `Параметры` -> `система` -> `компоненты` -> `Zapret` -> `"Обновить/переустановить"`
2. **Включите ручной ввод параметров.** Перейдите в настройки компонента Zapret и включите ручной ввод параметров. 
3. **Перейдите в директорию пресетов.** В разделе "Работа с пресетами" нажмите "Загрузить настройки из файла". Перейдите в директорию с программой и откройте `"_internal\data\settings\presets\zapret"` 
4. **Выберите рабочий пресет.** Подберите рабочую конфигурацию из `5.json - 12.json` файлов

**Comment by xleb-normal** [comment]
С 5.json заработало, спасибо!

**Comment by xleb-normal** [comment]
Теперь при каждом запуске zapret перестаёт работать и выдаёт ошибку, но после перезапуска процесса всё работает нормально. Вся папка goodbyedpi UI добавлена в белый список антивируса
[DEBUG] Connecting to winws.exe ...

 --debug=0|1|syslog|@<filename>

aemon                                       ; daemonize

 --pidfile=<filename>                           ; write pid to file

 --ctrack-timeouts=S:E:F[:U]                    ; internal conntrack timeouts fo

r TCP SYN, ESTABLISHED, FIN stages, UDP timeout. default 60:300:60:60



WINDIVERT FILTER:

 --wf-iface=<int>[.<int>]                       ; numeric network interface and 

subinterface indexes

 --wf-l3=ipv4|ipv6                              ; L3 protocol filter. multiple c

omma separated values allowed.

 --wf-tcp=[~]port1[-port2]                      ; TCP port filter. ~ means negat

ion. multiple comma separated values allowed.

 --wf-udp=[~]port1[-port2]                      ; UDP port filter. ~ means negat

ion. multiple comma separated values allowed.

 --wf-raw=<filter>|@<filename>                  ; raw windivert filter string or

 filename

 --wf-save=<filename>                           ; save windivert filter string t

o a file and exit



LOGICAL NETWORK FILTER:

 --ssid-filter=ssid1[,ssid2,ssid3,...]          ; enable winws only if any of sp

ecified wifi SSIDs connected

 --nlm-filter=net1[,net2,net3,...]              ; enable winws only if any of sp

ecified NLM network is connected. names and GUIDs are accepted.

 --nlm-list[=all]                               ; list Network List Manager (NLM

) networks. connected only or all.


MULTI-STRATEGY:

 --new                                          ; begin new strategy

 --filter-l3=ipv4|ipv6                          ; L3 protocol filter. multiple c

omma separated values allowed.

 --filter-tcp=[~]port1[-port2]                  ; TCP port filter. ~ means negat

ion. setting tcp and not setting udp filter denies udp.

 --filter-udp=[~]port1[-port2]                  ; UDP port filter. ~ means negat

ion. setting udp and not setting tcp filter denies tcp.

 --filter-l7=[http|tls|quic|wireguard|dht|unknown] ; L6-L7 protocol filter. mult

iple comma separated values allowed.

 --ipset=<filename>                             ; ipset include filter (one ip/C

IDR per line, ipv4 and ipv6 accepted, gzip supported, multiple ipsets allowed)  

 --ipset-exclude=<filename>                     ; ipset exclude filter (one ip/C

IDR per line, ipv4 and ipv6 accepted, gzip supported, multiple ipsets allowed)  


HOSTLIST FILTER:

 --hostlist=<filename>                          ; apply dpi desync only to the l

isted hosts (one host per line, subdomains auto apply, gzip supported, multiple 

hostlists allowed)

 --hostlist-exclude=<filename>                  ; do not apply dpi desync to the

 listed hosts (one host per line, subdomains auto apply, gzip supported, multipl

e hostlists allowed)

 --hostlist-auto=<filename>                     ; detect DPI blocks and build ho

stlist automatically

 --hostlist-auto-fail-threshold=<int>           ; how many failed attempts cause

 hostname to be added to auto hostlist (default : 3)

 --hostlist-auto-fail-time=<int>                ; all failed attemps must be wit

hin these seconds (default : 60)

 --hostlist-auto-retrans-threshold=<int>        ; how many request retransmissio

ns cause attempt to fail (default : 3)

 --hostlist-auto-debug=<logfile>                ; debug auto hostlist positives 


TAMPER:

 --wsize=<window_size>[:<scale_factor>]         ; set window size. 0 = do not mo

dify. OBSOLETE !

 --wssize=<window_size>[:<scale_factor>]        ; set window size for server. 0 

= do not modify. default scale_factor = 0.

 --wssize-cutoff=[n|d|s]N                       ; apply server wsize only to pac

ket numbers (n, default), data packet numbers (d), relative sequence (s) less th

an N

 --hostcase                                     ; change Host: => host:

 --hostspell                                    ; exact spelling of "Host" heade

r. must be 4 chars. default is "host"

 --hostnospace                                  ; remove space after Host: and a

dd it to User-Agent: to preserve packet size

 --domcase                                      ; mix domain case : Host: TeSt.c

Om

 --dpi-desync=[<mode0>,]<mode>[,<mode2>]        ; try to desync dpi state. modes

 : synack syndata fake fakeknown rst rstack hopbyhop destopt ipfrag1 disorder di

sorder2 split split2 ipfrag2 udplen tamper

 --dpi-desync-ttl=<int>                         ; set ttl for desync packet     

 --dpi-desync-ttl6=<int>                        ; set ipv6 hop limit for desync 

packet. by default ttl value is used.

 --dpi-desync-autottl=[<delta>[:<min>[-<max>]]] ; auto ttl mode for both ipv4 an

d ipv6. default: 1:3-20

 --dpi-desync-autottl6=[<delta>[:<min>[-<max>]]] ; overrides --dpi-desync-autott

l for ipv6 only

 --dpi-desync-fooling=<mode>[,<mode>]           ; can use multiple comma separat

ed values. modes : none md5sig ts badseq badsum datanoack hopbyhop hopbyhop2    

 --dpi-desync-repeats=<N>                       ; send every desync packet N tim

es

 --dpi-desync-skip-nosni=0|1                    ; 1(default)=do not act on Clien

tHello without SNI (ESNI ?)

 --dpi-desync-split-pos=<1..9216>               ; data payload split position   

 --dpi-desync-split-http-req=method|host        ; split at specified logical par

t of plain http request

 --dpi-desync-split-tls=sni|sniext              ; split at specified logical par

t of TLS ClientHello

 --dpi-desync-split-seqovl=<int>                ; use sequence overlap before fi

rst sent original split segment

 --dpi-desync-split-seqovl-pattern=<filename>|0xHEX ; pattern for the fake part 

of overlap

 --dpi-desync-ipfrag-pos-tcp=<8..9216>          ; ip frag position starting from

 the transport header. multiple of 8, default 8.

 --dpi-desync-ipfrag-pos-udp=<8..9216>          ; ip frag position starting from

 the transport header. multiple of 8, default 32.

 --dpi-desync-badseq-increment=<int|0xHEX>      ; badseq fooling seq signed incr

ement. default -10000

 --dpi-desync-badack-increment=<int|0xHEX>      ; badseq fooling ackseq signed i

ncrement. default -66000

 --dpi-desync-any-protocol=0|1                  ; 0(default)=desync only http an

d tls  1=desync any nonempty data packet

 --dpi-desync-fake-http=<filename>|0xHEX        ; file containing fake http requ

est

 --dpi-desync-fake-tls=<filename>|0xHEX         ; file containing fake TLS Clien

tHello (for https)

 --dpi-desync-fake-unknown=<filename>|0xHEX     ; file containing unknown protoc

ol fake payload

 --dpi-desync-fake-syndata=<filename>|0xHEX     ; file containing SYN data paylo

ad

 --dpi-desync-fake-quic=<filename>|0xHEX        ; file containing fake QUIC Init

ial

 --dpi-desync-fake-wireguard=<filename>|0xHEX   ; file containing fake wireguard

 handshake initiation

 --dpi-desync-fake-dht=<filename>|0xHEX         ; file containing DHT protocol f

ake payload (d1...e)

 --dpi-desync-fake-unknown-udp=<filename>|0xHEX ; file containing unknown udp pr

otocol fake payload

 --dpi-desync-udplen-increment=<int>            ; increase or decrease udp packe

t length by N bytes (default 2). negative values decrease length.

 --dpi-desync-udplen-pattern=<filename>|0xHEX   ; udp tail fill pattern

 --dpi-desync-start=[n|d|s]N                    ; apply dpi desync only to packe

t numbers (n, default), data packet numbers (d), relative sequence (s) greater o

r equal than N

 --dpi-desync-cutoff=[n|d|s]N                   ; apply dpi desync only to packe

t numbers (n, default), data packet numbers (d), relative sequence (s) less than

 N


[DEBUG] The winws.exe process has been terminated for unknown reason

**Comment by Storik4pro** [comment]
Похоже, что zapret не понимает какой-то параметр. После чего появилась ошибка?

**Comment by xleb-normal** [comment]
> Похоже, что zapret не понимает какой-то параметр. После чего появилась ошибка?

После того как я включил 5 пресет из "_internal\data\settings\presets\zapret" (попробовал с 6 всё так-же, скорее всего так будет происходить и с остальными), ошибка возникает после того как программа запускается вместе с системой, но после того как я нажимаю "Перезапустить процесс" то всё начинает работать

**Comment by Storik4pro** [comment]
Я не вижу в вашем выводе строки `"winws: unknown option -- <option>"`. Если она есть, то, на какую опцию жалуется zapret?

**Comment by xleb-normal** [comment]
> Я не вижу в вашем выводе строки `"winws: unknown option -- <option>"`. Если она есть, то, на какую опцию жалуется zapret?

Без понятия, я полностью скопировал вывод, но мне получилось записать видео с тем как происходит ошибка. Может можно как-нибудь добавить параметр, который бы позволял перезапускать процесс winws.exe, чтобы ошибка не происходила?

https://github.com/user-attachments/assets/b75efa88-40a9-44c3-8231-4d7ec63ee647

**Comment by Storik4pro** [comment]
Я исследую эту проблему. Вероятно, программа при автозапуске передаёт неверные параметры из-за наличия пробелов в пути к программе

Что можно сделать прямо сейчас:

1. Скопируйте строку запуска из поля `"Дополнительные параметры"`
2. В разделе `"Работа с пресетами"` нажмите `"Сбросить до значений по умолчанию" `
3. В поле `"Дополнительные параметры"` вставьте параметры запуска

**Comment by xleb-normal** [comment]
> Я исследую эту проблему. Вероятно, программа при автозапуске передаёт неверные параметры из-за наличия пробелов в пути к программе
> 
> Что можно сделать прямо сейчас:
> 
> 1. Скопируйте строку запуска из поля `"Дополнительные параметры"`
> 2. В разделе `"Работа с пресетами"` нажмите `"Сбросить до значений по умолчанию" `
> 3. В поле `"Дополнительные параметры"` вставьте параметры запуска

Помогло!

**Comment by gremilkar** [comment]
> С 5.json заработало, спасибо!

Спасибо,у меня тоже заработало)

**Comment by sergcj6** [comment]
При любой настройки запрета, всё равно циклична подключение к RTC

**Comment by Storik4pro** [comment]
> При любой настройки запрета, всё равно циклична подключение к RTC

Обновите zapret ещё раз. 
В поле "дополнительные параметры" вставьте следующую строку
```
--wf-tcp 80,443 --wf-udp 443,50000-50099 --filter-tcp 80 --dpi-desync fake,split2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --hostlist-auto autohostlist.txt --new --filter-tcp 443 --hostlist list-youtube.txt --dpi-desync fake,split2 --dpi-desync-repeats 11 --dpi-desync-fooling md5sig --dpi-desync-fake-tls tls_clienthello_www_google_com.bin --new --filter-tcp 80,443 --dpi-desync fake,disorder2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --new --filter-udp 50000-50099 --ipset ipset-discord.txt --dpi-desync fake --dpi-desync-repeats 6 --dpi-desync-any-protocol --dpi-desync-cutoff n4 --new --filter-udp 443 --hostlist list-youtube.txt --dpi-desync fake --dpi-desync-repeats 11 --dpi-desync-fake-quic quic_initial_www_google_com.bin --new --filter-udp 443 --dpi-desync fake --dpi-desync-repeats 11
```
Если ничего не работает, то придется искать параметры запуска вручную. 

Соответствующие обсуждения можно найти здесь:
1. https://github.com/Flowseal/zapret-discord-youtube/discussions/252?sort=new
2. https://github.com/bol-van/zapret/issues/672

**Comment by 4521-andreevich** [comment]
Голосовой чат в дискорде не работает, перепробовал всё что можно было. Подскажите кто-нибудь решение данной проблемы

**Comment by Storik4pro** [comment]
@4521-andreevich 
Попробуйте остановить все связанные с обходом DPI службы и повторить снова:
```
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc stop "WinDivert"
sc delete "WinDivert"
sc stop "WinDivert14"
sc delete "WinDivert14"
```
Так же запустите `killall.exe` из папки компонента zapret

**Comment by 4521-andreevich** [comment]
> @4521-andreevich попробуйте остановить все, что связано с обходом службы DPI, и запустите снова:
> 
> ```
> sc stop "GoodbyeDPI"
> sc delete "GoodbyeDPI"
> sc stop "WinDivert"
> sc delete "WinDivert"
> sc stop "WinDivert14"
> sc delete "WinDivert14"
> ```
> 
> Так же запустите `killall.exe`из папок компонент zapret

Не помогло

**Comment by 4521-andreevich** [comment]
> @4521-andreevich, пока что могу посоветовать настроить параметры запуска вручную. Я сообщу, когда смогу найти новую схему для дискорда.

Хорошо, пока что буду использовать платный VPN

**Comment by 45SADERT45** [comment]
Не работает ни 1 стратегия zapret дискорду просто всеравно, причем, что странно на ноуте который подключен к тому же интернету все работает, ошибок нет, все запускается, но дискорд просто крутит и все, с впн все нормально стартует, но юзать его вместе с играми такое себе решение.

**Comment by xleb-normal** [comment]
Вопрос не относящийся к теме, можно в следующем обновлении добавить в список обхода steam на всякий случай

**Comment by Storik4pro** [comment]
> Вопрос не относящийся к теме, можно в следующем обновлении добавить в список обхода steam на всякий случай

Скорее нет, чем да. Я пока что занят другими делами, связанными с UI. Если подберешь IP самостоятельно, то можешь создать соответствующий Pull requests в [репозитории с конфигурациями](https://github.com/Storik4pro/goodbyeDPI-UI-configs)

**Comment by xleb-normal** [comment]
> > Вопрос не относящийся к теме, можно в следующем обновлении добавить в список обхода steam на всякий случай
> 
> Скорее нет, чем да. Я пока что занят другими делами, связанными с UI. Если подберешь IP самостоятельно, то можешь создать соответствующий Pull requests в [репозитории с конфигурациями](https://github.com/Storik4pro/goodbyeDPI-UI-configs) 

А нужны именно ip или домены тоже сойдут?

**Comment by Storik4pro** [comment]
> > > Вопрос не относящийся к теме, можно в следующем обновлении добавить в список обхода steam на всякий случай
> > 
> > 
> > Скорее нет, чем да. Я пока что занят другими делами, связанными с UI. Если подберешь IP самостоятельно, то можешь создать соответствующий Pull requests в [репозитории с конфигурациями](https://github.com/Storik4pro/goodbyeDPI-UI-configs)
> 
> А нужны именно ip или домены тоже сойдут?

Доменов должно хватить

**Comment by sergcj6** [comment]
Ничего в общем не помогает. Будем ждать

**Comment by Storik4pro** [comment]
> > @4521-andreevich, пока что могу посоветовать подобрать параметры запуска вручную. Я сообщу, когда смогу найти новые конфигурации для дискорда
> 
> Пока нет новостей?

Посмотрите в #31

**Comment by 4521-andreevich** [comment]
> > > @4521-andreevich, пока что могу посоветовать подобрать параметры запуска вручную. Я сообщу, когда смогу найти новые конфигурации для дискорда
> > 
> > 
> > Пока нет новостей?
> 
> Посмотрите в #31

Не помогло...

**Comment by ofry** [comment]
А для GoodByeDPI есть ли какое-либо решение?

**Comment by Storik4pro** [comment]
@Lindsaydoodle руководство #31 было обновлено. Попробуйте новые способы описанные в нем

**Comment by Storik4pro** [comment]
> > [@Lindsaydoodle](https://github.com/Lindsaydoodle) руководство [#31](https://github.com/Storik4pro/goodbyeDPI-UI/issues/31) было обновлено. Попробуйте новые способы описанные в нем
> 
> оки попробую а есть варианты чтобы zapret или beydpi не детектились call of duty warzone?

Теоретически настройка Byedpi для UDP+TCP не должна определяться античитом, но у меня не было возможности это протестировать. Так же вам придется вручную найти параметры запуска т.к. автоподбор для byedpi пока что не работает.
Я могу посоветовать посмотреть стратегии для Byedpi в [группе стратегий для ByeByeDPI](https://t.me/byebyedpi_group/21941)
Так же можете скачать приложение [ByeByeDPI](https://github.com/romanvht/ByeDPIAndroid) на ваш телефон и выполнить подбор параметров там после чего перенести параметры на ПК (см [wiki/byebyedpi-cross-config/](https://storik4pro.github.io/wiki/byebyedpi-cross-config/)). Как правило параметры с -Ku работают для UDP
