### ISSUE TITLE
Добавление селекта выбора компонента обхода блокировки в маленьком окошке

### ISSUE THREAD

**Issue by aczamaz** [Storik4pro/goodbyeDPI-UI#17]
можно ли добавить селект в это окошко вот сюда
![image](https://github.com/user-attachments/assets/78105116-afb3-4010-879b-dcf33bff8ee8)
в котором бы можно было бы выбирать активный компонент который сейчас правится только в настройках
![image](https://github.com/user-attachments/assets/de4759fe-371d-4805-8ab2-62499162b803)
просто бывают случай когда один компонент помогает для одних сайтов а другой для других, было бы удобно их переключать в маленьком окошке а не переходить каждый раз настройки?

**Comment by Storik4pro** [comment]
Было добавлено в [обновлении 1.2.1](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.21)
