### ISSUE TITLE
Не отображается содержимое окна приложения на дисплее

### ISSUE THREAD

**Issue by Studyoz** [Storik4pro/goodbyeDPI-UI#18]
![Бес имени](https://github.com/user-attachments/assets/d553fe75-53e9-4162-b155-86e648210307)
Делаю скрины - на них вижу это

![IMG22](https://github.com/user-attachments/assets/cb78a9ce-4431-4946-bde4-2dc7991841a5)
А на экране монитора вот это

Возможно, это не относится к самому приложению, но такое я вижу впервые.

**Comment by Studyoz** [comment]
"А вы знали?" со скрина в этой ситуации приобретает действительно глубокие смыслы

**Comment by Storik4pro** [comment]
> "А вы знали?" со скрина в этой ситуации приобретает действительно глубокие смыслы

Да, звучит забавно. 

Попробуйте кликнуть на то место, где находится кнопка `"Открыть параметры"` и в разделе `"персонализация"` отключите размытие Mica

**Comment by Studyoz** [comment]
![IMG](https://github.com/user-attachments/assets/dd3b0214-c2c5-4021-a7dd-86cfea0ab6b1)
Да. Спасибо.

А что именно не сработало, если не сложно?..

**Comment by Storik4pro** [comment]
> А что именно не сработало, если не сложно?..

Вообще, применение эффекта размытия Mica в Win32 приложениях работает не стабильно. Возможно, проблема на стороне системы или приложение не верно применило эффект.
Вариантов много

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.1](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.1)
