### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by seshty** [Storik4pro/goodbyeDPI-UI#19]
![photo_2024-10-30_21-35-47](https://github.com/user-attachments/assets/8abb3942-8f61-42c5-8d07-90759a85421d)

**Comment by Storik4pro** [comment]
Попробуйте принудительно запустить программу от имени администратора

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.1](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.1)
