### ISSUE TITLE
Неочевидно как добавить свои хосты в zapret

### ISSUE THREAD

**Issue by MrGreenier** [Storik4pro/goodbyeDPI-UI#20]
Zapret работает, использую если что json конфиг. Но работает только Ютуб и Дискорд. Добавлял в general txt, какие то сайты работают, какие то нет, Инстаграм к примеру вообще не открывается.

**Comment by PhantomX5571** [comment]
Теперь можно менять список сайтов для запрета, используя путь _internal\data\zapret. Файлы находятся list-discord.txt(для обхода RTS - вызовов) и list-youtube.txt. В дальнейшем соответствующая кнопка появится в параметрах.
P.S
Спасибо @Storik4pro

**Comment by Storik4pro** [comment]
#13

**Comment by Storik4pro** [comment]
Было добавлено в [обновлении 1.2.2](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.2)
