### ISSUE TITLE
False positive ESET NOD32

### ISSUE THREAD

**Issue by gremilkar** [Storik4pro/goodbyeDPI-UI#21]
Обнаружил,что после обновления,Eset Nod32 Antivirus   18.0.11.0 стал определять goodbyeDPI.exe как подозрительный (suspicious).: 31.10.2024 13:18:20;Real-time file system protection;file;C:\Program Files\GoodbyeDPI_UI\goodbyeDPI.exe;Suspicious Object;retained;PCNAME\CurrentUser;Event occurred during an attempt to access the file by the application: C:\Program Files\ESET\ESET Security\egui.exe (1D9C16E1D6343DFA895CC7F308FAC9E53F2A6C82).;D175A9A2EFB39B394195E9160734941DF9DFCA83;15.10.2024 9:41:25

**Comment by Storik4pro** [comment]
Многие антивирусы ложно определяют приложение как вирус из-за запроса прав администратора.
Я постараюсь исправить эту проблему в следующем обновлении

**Comment by Storik4pro** [comment]
Было частично исправлено в [обновлении 1.2.1](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.1)
