### ISSUE TITLE
Не запускается ютуб через GoodbyeDPI

### ISSUE THREAD

**Issue by TSHADET** [Storik4pro/goodbyeDPI-UI#23]
Переустанавливал отдельно компонент, прогу полностью, переделывал пресеты, в БЕТА помощнике с пресетами по GoodbyeDPI выдает пресет самый быстрый, через него тоже не запускается

**Comment by Storik4pro** [comment]
Для zapret попробуйте воспользоваться руководством #15. 
Если не хотите использовать zapret, то скачайте [GoodCheck](https://ntc.party/t/goodcheck-%D0%B1%D0%BB%D0%BE%D0%BA%D1%87%D0%B5%D0%BA-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82-%D0%B4%D0%BB%D1%8F-goodbyedpi-zapret-byedpi/10880/1021). В оригинальной версии подбор параметров совершеннее, чем в порте

**Comment by TSHADET** [comment]
Как раз на этой статье и изменял предметы для zapret. ДС стал работать, но не Ютуб, попробую то что скинули

**Comment by TSHADET** [comment]
Я переустановил по новой прогу, Ютуб заработал на дефолтных настройках. Дискорд кстати тоже
