### ISSUE TITLE
Краш при авто запуске

### ISSUE THREAD

**Issue by xleb-normal** [Storik4pro/goodbyeDPI-UI#25]
---------------------------
GoodbyeDPI UI
---------------------------
Unable to start application
Application version: 1.2.1
System information: Windows 10.0.19045 64bit
Error type: CRITICAL ERROR
Details:
-----
Traceback (most recent call last):
  File "C:\Users\Xleb\Desktop\GOODBY~1\main.py", line 101, in <module>
NameError: name 'options' is not defined

-----
Press CTRL+C to copy error output.

If this error persists, please contact app support and report the issue.
---------------------------
ОК   
---------------------------

после запуска вручную всё работает прекрасно

**Comment by Storik4pro** [comment]
Направлю исправление как можно скорее. 

**Что можно сделать прямо сейчас:**
Перейдите в `планировщик заданий` -> `GoodbyeDPI_UI_autorun` -> `Свойства` -> `Действия` -> `Изменить` -> В поле `"Добавить аргументы"` удалите `--autorun`. 
Сохраните изменения.
После этого перейдите в параметры приложения -> `Система` -> `Скрывать программу в трей при запуске`

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.1.1](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.1.1)
