### ISSUE TITLE
Статус процесса на домашней странице отображается некорректно при автозапуске

### ISSUE THREAD

**Issue by Iowerth** [Storik4pro/goodbyeDPI-UI#28]
Windows 10 x64.
gDPI-UI 1.2.1.1.

В настройках выставлен автозапуск, но при старте ПК запускается только приложение, но не обход. В версии 1.2.0 это работало корректно.
<details>
<summary>Скриншоты</summary>

![goodbyeDPI_040dSYp4Kz](https://github.com/user-attachments/assets/14d02209-f6f5-40e9-8f31-55ce46bfa783)

![goodbyeDPI_3dO3TReApk](https://github.com/user-attachments/assets/d10e0764-15b5-47c2-abf3-a0f6ec664025)

![goodbyeDPI_IgBwScNTRb](https://github.com/user-attachments/assets/706773c6-d5fe-42e5-8c2b-0d4948e6699f)
</details>

~~Но вообще, обход при этом, судя по всему, работает.~~ Не работает.

Может, флаг запущенного приложения некорректно отображается в интерфейсе?

**Comment by Storik4pro** [comment]
Проверьте через инструмент "Просмотреть вывод", запускается ли zapret при автозапуске

**Comment by Iowerth** [comment]
@Storik4pro я разобрался - это баг интерфейса. Неважно, что используешь - автозапуск или запуск через ПКМ в трее - всё равно в интерфейсе приложения флаг напротив "Запуск" не выставляется в состояние запущенного.

**Comment by Storik4pro** [comment]
Хорошо. Исправлю в следующем обновлении

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.2](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.2)
