### ISSUE TITLE
Ошибка при обновлении с 1.2.1.1 до 1.2.2

### ISSUE THREAD

**Issue by Iowerth** [Storik4pro/goodbyeDPI-UI#32]
Windows 10 x64.

Во-первых, спасибо за обновление!
В очередной раз попытался обновить из-под программы (обычно обновляю руками портабл-версию, что пришлось сделать еще раз и сейчас после ошибки), но вылезла ошибка:
<details>
  <summary>Скриншот</summary>

![siZvCWS9sX](https://github.com/user-attachments/assets/86e1ead2-cf27-4be8-b20a-d99e20d0d958)
</details>

**Comment by Storik4pro** [comment]
Спокойно пропускайте. Эта динамическая библиотека не обновляется

**Comment by Iowerth** [comment]
Спасибо, учту.
Может, стоит добавить какое-то уведомление об этом? Или скрыть это вообще?

**Comment by Storik4pro** [comment]
Вы правы, в следующем обновлении добавлю исключение в Update Assistant

**Comment by Iowerth** [comment]
Спасибо за обновление! Но опять вылезла та же ошибка:
<details>
  <summary>Скриншот</summary>

![A23hEjuLai](https://github.com/user-attachments/assets/914b2809-cf55-437c-96f9-5ba41f79bf25)
</details>

Как вы рекомендовали, я пропустил ее, и всё норм установилось.

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.3](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.3). Изменения применятся начиная с версии 1.2.3 из-за особенностей процесса обновления
