### ISSUE TITLE
Несоответствие статуса в трее и в программе

### ISSUE THREAD

**Issue by Iowerth** [Storik4pro/goodbyeDPI-UI#33]
В продолжение https://github.com/Storik4pro/goodbyeDPI-UI/issues/28
Windows 10 x64.
gDPI-UI 1.2.2.

Если в программе выставлено "Запуск - Вкл", то в трее видно "Остановка", что верно. Но стоит нажать в трее на "Остановка", то в программе флаг остается в значении "Вкл".
В остальных случаях вроде всё в порядке, пока заметил только описанное.

Как вариант, в дополнение - менять цвет значка в трее на красный, если сервис не запущен, и на зеленый, если запущен. Так уже было сделано в одном UI, очень удобно.

**Comment by Storik4pro** [comment]
> Если в программе выставлено "Запуск - Вкл", то в трее видно "Остановка", что верно. Но стоит нажать в трее на "Остановка", то в программе флаг остается в значении "Вкл".
> В остальных случаях вроде всё в порядке, пока заметил только описанное.

Было исправлено в [обновлении 1.2.3](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.3)

> Как вариант, в дополнение - менять цвет значка в трее на красный, если сервис не запущен, и на зеленый, если запущен. Так уже было сделано в одном UI, очень удобно.

Было добавлено в [обновлении 1.2.3](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.3)
