### ISSUE TITLE
I didn't understand anything, but I see this error

### ISSUE THREAD

**Issue by Rograr** [Storik4pro/goodbyeDPI-UI#35]
---------------------------
GoodbyeDPI UI
---------------------------
Unable to start application
Application version: 1.2.2
System information: Windows 10.0.26100 64bit
Error type: CRITICAL ERROR
Details:
-----
Traceback (most recent call last):
  File "C:\PROGRA~1\GOODBY~1\main.py", line 116, in <module>
  File "C:\PROGRA~1\GOODBY~1\quick_start.py", line 28, in check_app_is_runned
SystemExit: 0

-----
Press CTRL+C to copy error output.

If this error persists, please contact app support and report the issue.
---------------------------
ОК   
---------------------------

**Comment by Storik4pro** [comment]
This error appeared after clicking `"NO"` in the `"The goodbyeDPI.exe process is already running. Do you want to terminate it and start a new instance"`?

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.3](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.3)

**Comment by Kislotik** [comment]
---------------------------
GoodbyeDPI UI
---------------------------
Unable to start application
Application version: -x-
System information: Windows 6.3.9600 64bit
Error type: CRITICAL ERROR
Details:
-----
Traceback (most recent call last):
  File "C:\PROGRA~1\GOODBY~1\main.py", line 13, in <module>
  File "C:\PROGRA~1\GOODBY~1\qasync\__init__.py", line 81, in <module qasync>
  File "importlib.py", line 126, in import_module
ImportError

-----
Press CTRL+C to copy error output.

If this error persists, please contact app support and report the issue.
---------------------------
ОК   
---------------------------
????

**Comment by Storik4pro** [comment]
> ## GoodbyeDPI UI
> ## Unable to start application
> Application version: -x-
> System information: Windows 6.3.9600 64bit
> Error type: CRITICAL ERROR
> Details:
> Traceback (most recent call last): File "C:\PROGRA~1\GOODBY~1\main.py", line 13, in File "C:\PROGRA~1\GOODBY~1\qasync__init__.py", line 81, in File "importlib.py", line 126, in import_module ImportError
> 
> Press CTRL+C to copy error output.
> 
> ## If this error persists, please contact app support and report the issue.
> ## ОК
> ????

#54
