### ISSUE TITLE
Непонятный баг при попытке запуска запрет

### ISSUE THREAD

**Issue by DummyTheAllSeeing** [Storik4pro/goodbyeDPI-UI#38]
Вывод:
[DEBUG] Connecting to winws.exe...

we have 10 user defined desync profile(s) and default low priority profile 0
iles\GoodbyeDPI_UI\data\zapret\winws.exeLoading hostlist autohostlist.txt    
loading plain text list
Loaded 0 hosts from autohostlist.txt 
Loading hostlist list-discord.txt    
loading plain text list
Loaded 35 hosts from list-discord.txt
Loading hostlist myhostlist.txt      
loading plain text list
Loaded 6 hosts from myhostlist.txt   
Loading hostlist russia-blacklist.txt
loading plain text list
Loaded 146341 hosts from russia-blacklist.txt
Loading hostlist russia-youtube.txt     
loading plain text list
Loaded 20 hosts from russia-youtube.txt 
Loading hostlist russia-youtubeGV.txt   
loading plain text list
Loaded 1 hosts from russia-youtubeGV.txt
Loading hostlist russia-youtubeQ.txt    
loading plain text list
Loaded 7 hosts from russia-youtubeQ.txt 
Loading hostlist netrogat.txt
loading plain text list
Loaded 2 hosts from netrogat.txt
windivert: error opening filter: The service cannot be started, either because i
t is disabled or because it has no enabled devices associated with it.

[ERROR] Unknown error occurred while process running

**Comment by DummyTheAllSeeing** [comment]
я тупенький немножко, извиняюсь

**Comment by Min1raft** [comment]
Как решил?
