### ISSUE TITLE
Конфиги и задержка открытия настроек

### ISSUE THREAD

**Issue by LoST202** [Storik4pro/goodbyeDPI-UI#4]
Программа замечательная, но естт нюансы (лично мое мнение):
1. txt-файлы делались как-то странно, потому что в них многие сайты дублируются. Не проще тогда сделать единый?
2. Кнопка с настройками реагирует не сразу на нажатие (иногда срабатывает с седьмого раза)
3. Еще раз проверьте конфиги для всех программ, подтупливает
4. Добавить возможность самостоятельно добавлять свои сайты в исключения и проксирования?

Заранее спасибо :3

**Comment by Storik4pro** [comment]
1. `.txt` файлы существуют отдельно для zapret и goodbyeDPI. Это не удобно, понимаю. Я подумаю над улучшением этого аспекта
2. О том, что параметры открываются с задержкой я знаю. Прямо сейчас это приоритетная проблема. Пока что могу посоветовать не нажимать много раз на кнопку открытия параметров. Если вы нажали один раз - параметры обязательно откроются 
3. Не совсем понял на счёт последнего

**Comment by LoST202** [comment]
> 1. `.txt` файлы существуют отдельно для zapret и goodbyeDPI. Это не удобно, понимаю. Я подумаю над улучшением этого аспекта
> 2. О том, что параметры открываются с задержкой я знаю. Прямо сейчас это приоритетная проблема. Пока что могу посоветовать не нажимать много раз на кнопку открытия параметров. Если вы нажали один раз - параметры обязательно откроются
> 3. Не совсем понял на счёт последнего

**Comment by LoST202** [comment]
> 1. `.txt` файлы существуют отдельно для zapret и goodbyeDPI. Это не удобно, понимаю. Я подумаю над улучшением этого аспекта
> 2. О том, что параметры открываются с задержкой я знаю. Прямо сейчас это приоритетная проблема. Пока что могу посоветовать не нажимать много раз на кнопку открытия параметров. Если вы нажали один раз - параметры обязательно откроются
> 3. Не совсем понял на счёт последнего

Ну, многие сайты которые в обычном GDP или zapret открываются в вашей программе не работают (либо делают это почему то некорректно). Также я пытался вручную вносить сайты в списки, но после перезапуска это не помогало

**Comment by Storik4pro** [comment]
Возможно, ваши настройки не совпадают с предустановленными в программе. 
Так же следует убедиться, что вы изменяете правильный файл (для goodbye DPI это `custom_blacklist.txt`)

**Comment by Storik4pro** [comment]
Возможно, ваши настройки не совпадают с предустановленными в программе. 
Так же следует убедиться, что вы изменяете правильный файл (для goodbye DPI это `custom_blacklist.txt`)

**Comment by Storik4pro** [comment]
Возможно, ваши настройки не совпадают с предустановленными в программе. 
Так же следует убедиться, что вы изменяете правильный файл (для goodbye DPI это `custom_blacklist.txt`)

**Comment by LoST202** [comment]
> Возможно, ваши настройки не совпадают с предустановленными в программе. Так же следует убедиться, что вы изменяете правильный файл (для goodbye DPI это `custom_blacklist.txt`)

Изменял я настройки zapret. Файлы прежде чем модифицировать я проверяю

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.1](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.1)
