### ISSUE TITLE
myhostlist.txt

### ISSUE THREAD

**Issue by zaeboba** [Storik4pro/goodbyeDPI-UI#44]
какой ты молодец, после обновы все мои списки слетели из myhostlist.txt, большое спасибо.

**Comment by Storik4pro** [comment]
Скорее всего эта проблема связана с обновлением компонентов. Исправлю в следующем обновлении

**Comment by Storik4pro** [comment]
Было исправлено в [обновлении 1.2.4](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.4)
