### ISSUE TITLE
Добавить ipset-discord.txt в пресет YTDisBystro by KDS

### ISSUE THREAD

**Issue by xleb-normal** [Storik4pro/goodbyeDPI-UI#45]
Если в пресете отсутствует файл `ipset-discord.txt`, то при попытке подключиться к войсу в Discord  весит бесконечное подключение к RTC. Было бы логично добавить этот файл в пресет по умолчанию, чтобы пользователям не приходилось лазить в настройках

**Comment by Storik4pro** [comment]
Это не имеет смысла. Невозможность подключения не связана с отсутствием или наличием `ipset-discord.txt`. Данный пресет, как правило, работает у большинства пользователей, из-за чего он отмечен как `"По умолчанию"`

**Comment by xleb-normal** [comment]
> Это не имеет смысла. Невозможность подключения не связана с отсутствием или наличием `ipset-discord.txt`. Данный пресет, как правило, работает у большинства пользователей, из-за чего он отмечен как `"По умолчанию"`

Ну ладно
