### ISSUE TITLE
Автозапуск обхода после обновления zapret

### ISSUE THREAD

**Issue by Iowerth** [Storik4pro/goodbyeDPI-UI#46]
Здравствуйте. Рассмотрите, пожалуйста, возможность автозапуска обхода после обновления zapret (не знаю, как с другими, просто использую только его).
Заходишь в компоненты, успешно обновляешь zapret, и приходится опять идти запускать обход.

**Comment by Storik4pro** [comment]
Было добавлено в [обновлении 1.2.4](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.4)
