### ISSUE TITLE
На версии Windows 11 24h2 26100.2314 не работают уведомления (несмотря на то, что на 24h2 26100.2033 они работали нормально)

### ISSUE THREAD

**Issue by EgorimM** [Storik4pro/goodbyeDPI-UI#49]
Здравствуйте.  Извините, что опять пишу я. 
Вчера "прилетело" обновление до 26100.2314 и после него перестали работать все уведомления от интерфейса-программы несмотря на то, что все уведомления исправно работали на 26100.2033. Программа конечно запущена от имени администратора (пробовал и без него - ничего не изменилось.). Путь не содержит пробелов или русских символов.
Попробовал решить проблему сам, но ничего не получилось. 
Это не критично, просто странно. На промежуточные сборки между 26100.2033 и 26100.2314 я не обновлялся (тем более совсем недавно переустановил винду именно 26100.2033), поэтому возможно уведомления "сломались" ещё на какой-либо промежуточной версии.
Ещё раз это не критично, просто сообщаю как странный баг (я исправил его банально - удалив это обновление).

https://github.com/user-attachments/assets/c2cb7315-74ae-46dd-9fbc-57a0f3fd7dfe

**Comment by Storik4pro** [comment]
Возможно, это связанно с изменением API уведомлений Windows. Так же, Windows может отключать уведомления для конкретных приложений. Проверьте настройки разрешений уведомлений для приложения

**Comment by EgorimM** [comment]
> Проверьте настройки разрешений уведомлений для приложения

Все настройки были по умолчанию. Но в списке приложений как и показано на видео Интерфейса не было.

Но после импортирования реестра с компьютера с рабочими уведомлениями и перерегистрацией приложения, уведомления заработали.

Параметры которые импортировал:

`Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings\GoodbyeDPI_app]
"LastNotificationAddedTime"=hex(b):cd,1b,da,bc,ba,45,db,01
"PeriodicNotificationCount"=dword:00000001`

Могу не аккуратно сделать вывод о том, что скорее всего у именно у меня просто произошёл баг регистрации приложения и поэтому не создался и профиль уведомлений. Странно что без этого профиля на 26100.2033 оно работало, ну да ладно.

**Comment by Storik4pro** [comment]
Похоже, что Windows отчистила реестр при обновлении.
Регистрацию приложения можно вызвать заново.
Для этого в файле настроек `data/settings/settings.ini` в разделе `GLOBAL` измените значение `is_first_run ` на `True`. Это заставит приложение повторно зарегистрировать себя

**Comment by EgorimM** [comment]
> Для этого в файле настроек `data/settings/settings.ini` в разделе `GLOBAL` измените значение `is_first_run ` на `True`. Это заставит приложение повторно зарегистрировать себя

Спасибо большое. Всё работает.
