### ISSUE TITLE
ctrl+v или win+v вызывают утечку памяти

### ISSUE THREAD

**Issue by leaftail1880** [Storik4pro/goodbyeDPI-UI#5]
Хотел вставить параметры вызова zapret, в итоге программа просто зависла и начала кушать память

Зависло все до такой степени, что даже встроенный в винду снимок экрана перестал работать, пришлось доставать телефон

В моменте потребление диска и памяти доходило до 100%

![изображение](https://github.com/user-attachments/assets/297faee2-5d90-448c-9a7b-bfcd264bd3dc)

Связанная проблема: при фокусе в окно программы не работает print screen

**Comment by leaftail1880** [comment]
Возможно, дело в том, что скопированные параметры содержат =, что является недопустимым символом в строке ввода (что странно)

и винда пытается этот символ написать, но у нее не получается, и она повторяет и повторяет, пока память не закончится

**Comment by Storik4pro** [comment]
Попробуйте ввести команду без знаков `=`. Для запрета не важно, есть знак равно или нет.

Проблема с print screen не связана с утечкой памяти. Это базовое поведение Win32 приложений. Вместо вызова средства создания скриншота делается системный скриншот всего экрана.

Утечка памяти происходит из-за несовершенности алгоритма проверки ввода. Я постараюсь исправить это как можно скорее

**Comment by Storik4pro** [comment]
Проблема была исправлена в обновлении [1.1.5](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.1.5)
