### ISSUE TITLE
Возможность быстро изменять список сайтов для goodcheck

### ISSUE THREAD

**Issue by SUPER-SERGIK** [Storik4pro/goodbyeDPI-UI#50]
Ну название само за себя говорит просто сейчас каждый раз нужно лезть куда-то в глубь компа, а так раз быстро поменял и всё...

**Comment by Storik4pro** [comment]
Было добавлено в [обновлении 1.2.4](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.2.4)
