### ISSUE TITLE
Некорректное определение наличия обновлений компонент.

### ISSUE THREAD

**Issue by lelicopter** [Storik4pro/goodbyeDPI-UI#53]
При отсутствии обновлений, приложение выдает сообщения об их наличии.
Возможно проблема связана с обновлением GoodbyeDPI:
Версия: test version - FWSNI support
Версия на сервере: 0.2.3rc3

Однако при обновлении:
![image](https://github.com/user-attachments/assets/6c91e62d-a3a3-40a2-a6f6-da8ff739defa)

**Comment by Storik4pro** [comment]
Какую версию GoodbyeDPI UI вы используете?

**Comment by lelicopter** [comment]
1.2.4.

**Comment by Storik4pro** [comment]
Откройте файл настроек `data/settings/settings.ini` и в разделе `COMPONENTS` измените параметр `goodbyedpi_server_version` на `test version - FWSNI support`

**Comment by lelicopter** [comment]
Похоже помогло!
